/** Canonical candidate profile (spec §3). Seeded on first login. */

import { BASE_CV } from "./base-cv";

export const CANDIDATE_PROFILE = {
  nombre: "Andrés Lince García",
  nickname: "Canelo",
  email: "canelopolymarket@gmail.com",
  ubicacion_actual: "Madrid, España",
  ciudadanias: ["ES", "CO"],
  work_permit_eu: true,
  idiomas: { es: "nativo", en: "profesional" },
  educacion: [
    {
      institucion: "IE Business School",
      programa: "International MBA",
      especializacion: "Entrepreneurship",
      graduacion: "2026-07-20",
    },
  ],
  experiencia_core: {
    empresa: "Colombina",
    años: 3,
    geografias: ["EMEA", "USA"],
    proyectos_cross_functional_emea: 35,
    clientes_b2b_usa: ["Walmart", "Costco", "Amazon"],
    metrica_destacada: "EBITDA +27%",
  },
  perfil_ai: {
    tipo: "constructor_hands_on",
    proyectos: ["Tiger_Bot", "Septia_AI", "Polymarket_trading"],
    descripcion:
      "No ingeniero tradicional. Constructor de sistemas autónomos apalancados por IA.",
  },
  goal_largo_plazo: "fundador",
  goal_corto_plazo: {
    tipo: "bridge_role",
    duracion_meses: 4,
    fecha_target: "2026-07",
  },
  target_roles_primary: [
    "Strategy Associate",
    "Strategy Manager",
    "Consultant",
    "Associate Consultant",
    "Business Operations",
    "BizOps",
    "Growth Operations",
    "Operations Manager",
    "Project Manager",
    "Program Manager",
    "Chief of Staff",
    "Founder's Associate",
    "AI Implementation Associate",
    "AI Implementation Manager",
    "AI Transformation Associate",
    "AI Operations",
    "Startup Operations",
    "Commercial Strategy",
    "GTM Strategy",
    "Strategic Partnerships",
    "Venture Operations",
  ],
  target_roles_secondary: [
    "Innovation",
    "Transformation",
    "Internal Strategy",
    "Expansion",
    "Product-adjacent business roles",
  ],
  geografia_prioridad: {
    1: "Madrid",
    2: "Bogotá",
    3: "Remote_elegible_desde_ES",
    4: "Remote_elegible_desde_CO",
    5: "España_broad",
    6: "Colombia_broad",
  },
  seniority_target: [
    "post_MBA_consultant",
    "associate",
    "junior_manager",
    "operations_manager",
  ],
  no_priorizar: ["internship", "trainee", "very_junior", "VP", "Head", "Director"],
  company_types_preferidos: [
    "tier_1_consulting",
    "tier_2_consulting",
    "strategic_roles_tech",
    "series_a_plus_con_traccion",
    "operadores_con_ejecucion_real",
  ],
  fit_signals_positivas: [
    "dual_ES_CO_EU_permit",
    "bilingue_ES_EN",
    "IE_MBA",
    "Colombina_EMEA_USA_3y",
    "Tiger_Bot_AI_implementation",
    "cross_functional_execution",
  ],
  fit_signals_caution: [
    "no_programador_formal",
    "no_referidos_MBB_tier_1",
    "SQL_gap_para_algunos_ops",
    "riesgo_sobrecualificacion_entry_level_europeo",
  ],
  base_cv: BASE_CV,
} as const;

export type CandidateProfile = typeof CANDIDATE_PROFILE;
